### PR TITLE
[WIP] Compiler optimization

### PR DESCRIPTION
**Pull request by thegrb93**
Just need to fix the raw tokens.

### CODE REVIEW

**Comment by thegrb93** [comment]
I've got it working. It doesn't save much time though. (Maybe 0.5 second for my 900line script).

The root of the compiler lag comes from something else (Maybe the thousands concatenations of each compiled segment of code). Let me know what you think. Do you think it's possible to collect all of the compiled code segments into a table and table.concat them in one big concat?

**Comment by oskar94** [comment]
Could you send me the script you are using to get the 19 seconds compile time? Would like to do some tests myself and see if i can find why it takes so long.

**Comment by thegrb93** [comment]
I'll put it in pastebin when I get home (In about 4 hours)

**Comment by thegrb93** [comment]
http://pastebin.com/vsR0Zyc5

**Comment by VINTproYKT** [comment]
Guys, is it working well? Just this pull request floats around with other opened.

**Comment by thegrb93** [comment]
Worked last time I tried.

**Comment by X-Coder** [comment]
Just tried it after merging into current HEAD. There was one none important conflict because of a indentation difference, and 34 other conflicts which could be resolved automatic by my merge tool. Bad thing: none of my scripts worked, blue screens because of compiler errors, and examples like the holo ball from wiki did not work too.

**Comment by thegrb93** [comment]
Guess its changed too much for this to be viable anymore. I'm not going to debug it since I've moved on to other things, but you guys really ought to look into using trees for compilation rather than string processing. Adios

**Pull request closed without merging**
