### PR TITLE
Fix unpack(table)

### PR DESCRIPTION
**Pull request by bigdogmat**
Title is pretty self explanatory.

### CODE REVIEW

**Comment by VINTproYKT** [comment]
Wondering why there was `not` operator :exclamation: 
Good :+1:

**Comment by bigdogmat** [comment]
Cause booleans :p

**Comment by ArmyArmyCz** [comment]
Is it tested?

**Comment by bigdogmat** [comment]
It isn't, though this is kind of fool proof.

Also it's made the same way unpack(array) is in a sense.

EDIT: Can't test as I only fixed this cause a friend asked me to, I don't have access to gmod atm so yea.

**Comment by ArmyArmyCz** [comment]
Well it shloudn't break anything, I just felt like asking.

**Comment by bigdogmat** [comment]
:p

**Pull request merged**
