### PR TITLE
Purge the string.format

### PR DESCRIPTION
**Pull request by thegrb93**
After a benchmark, I found that unnecessary string.format used for concatenation are 4x slower than normal concatenation. If you can go over my code and check for any mistakes it would be helpful.

### CODE REVIEW

**Comment by thegrb93** [comment]
Saves about 0.5 seconds for a 19 second compilation.

**Comment by VINTproYKT** [comment]
@Rusketh I think it's good remark. If it's truly time-eating, we must take this into account and don't use `string.format` in future versions.

@thegrb93 Can you please provide confirmation of that `string.format` is ~4 times slower than usual concatenation?

**Comment by bigdogmat** [comment]
This would be faster in normal Lua, though in LuaJIT it creates way too much garbage.

**Comment by thegrb93** [comment]
I wouldn't have spent so much time if I didn't test it first.

**Comment by thegrb93** [comment]
Btw, CapsAdmin introduced some huge string.gsub performance boosts you might look into. https://github.com/garrynewman/garrysmod/pull/1166

**Comment by Rusketh** [comment]
hmm

**Pull request closed without merging**
