### PR TITLE
[**Pending merge**] #292, #293 united + other fixes (into `master`)

### LINKED ISSUE #250: Issue: String Issues
I've noticed there are quite a few problems with the string methods, a couple i've run into brickwalls with are as follows:

1. Attempting to grab the name of another player's E2 via EA2 returns something along the lines of entity[%i]entity[%i].

2. While using the method player.tool(), using the method on a player other than yourself returns a lua error about it being a nil value and crashes the gate.

### PR DESCRIPTION
**Pull request by VINTproYKT**
All references (`@...`) are pointing to recent history commits.
- [x] Tests made, all works.
- [x] Compared with pure `master`, no conflicts.

## Done
I think these 8 issues (#288, #283, #277, #264, #262, #253, #250, #240) now can be closed to not mess with unsolved ones.

## Commits overview
* @da52e3a: `lua/expadv/editor/manual.lua`
 * @153d911 - More space for descriptions in manual
 * @d07c140 - Ultra-minor
 * @ca44696 - Sort every EA_HelpList by 3rd column. Looks pretty now
 * @119e236 - Alphabetical components tree
 * @12fca7e - Made classes menu sorted
 * @3ef874f - Put EA_HelpList descriptions into tooltip
* @7cc03d3: `lua/expadv/editor/ea_search.lua`
 * @ee15c8e - Faster search panel opening/closing
* @a11a446: lua/expadv/cppi.lua
 * @0e5187d - CPPI: GetOwner of Wire entities
* @f43868f: `lua/expadv/editor/ea_frame.lua`
 * @e97b922 - Force all frames to stay down with their roofs
 * @b9f3001 - Make frames not going out a vertical of the screen
* @45cf5fa: `lua/expadv/components/wire.lua`
 * @ccef853 - Added `linkWireIO` function into `wire` component
 * @012473b - linkWireIO - Check passage of prop protection check
 * @718d037 - Made linkWireIO global function in Lua environment + separation of VMFunctions ~~(depends on 5th arguments)~~
 * @5b49e87 - Unscoped EXPADV.linkWireIO
 * @d3edcdd - Removed Path from linkWireIO, cause it actually does nothing meaningful
* @ba19366: lua/expadv/editor/ea_editorpanel.lua
 * @b49901c - Added ability to share position and sizes of editor panel between **game** sessions. Saves them on close and shutdown.
* @365f09c: *`miscellaneous`*
 * @073ea8a - "r" - journey back
 * @1867241 - Grammar
* @efaa45e: `lua/expadv/components/number.lua`
 * @a159c2d - Added `sign`. Solves #288
* @cff12c3: `lua/expadv/editor/ea_editor.lua`
 * @8514e60 - Automatic outdent of right curly bracket in editor. Solves #283
 * @6b00c21 - Option added: `Bracket auto-outdentation`
* @3f5cead: `lua/expadv/components/wire.lua`
 * @3f5cead683eea8620e79bbe4117fdc33ac1dbbdf - Little mistake after uniting two pull requests
* @8ef33d0: `lua/expadv/components/android.lua`
 * @8ef33d0e3533327fd4a6f84449fc88369dae9dfc - Solves #277. Check that gate exists in `android` on every `onClick`, so it will not throw override error that prevents dialog from closing.
* @87c48e6: `lua/expadv/components/table.lua`
 * @87c48e60a8d8f6939bf31a69f32eb8c42b47fe15 - table.connect(table) fixed. Solves #264
* @694ae89: `lua/expadv/net.lua`
 * @694ae8974cbfec031c2fe70f8ed30c04e88da88d - Actually link entity to tab. Solves #262
* @725a723: `lua/expadv/components/color.lua`
 * @725a723ee26093560c90aa6da4ff4acf135cd30e - Color aliases color(N,M) and color(N)
* @22f059f: `lua/expadv/cppi.lua`
 * @22f059f2ddde00d1c88a76eed2eb1af91530b690 - Added get condition for ExpAdv's owner. Fixes #250
* @5cbc080: *`miscellaneous`*
 * @5cbc080be6968f48639c562da1e3178bbd5d726b - Netstream `readColor` fixed. Solves #240 
* @3ad92ab: `lua/expadv/components/table.lua`
 * @3ad92abbbc2a6904413b9fc32ab65bf3e71e8bd2 - Removed MsgN from `table`
* @95a7c9d: *`miscellaneous`*
 * @95a7c9dd8c9634ca0d5bb99b219d9282d88a0ef4 - Separated `wire` GetOwner and PPCheck
* @b9220bf: `lua/expadv/components/wire.lua`
 * @b9220bf0fe257ee75a23937af7538c3360a04d75 - Liquidated unnecessary `IsValid`

### CODE REVIEW

**Comment by ArmyArmyCz** [comment]
Everything fully tested?

**Comment by VINTproYKT** [comment]
@ArmyArmyCz I have tested all these before issue tracking and after. All works as expected.

**Comment by ArmyArmyCz** [comment]
There is some debug MsgN in table connect.

**Comment by VINTproYKT** [comment]
@ArmyArmyCz Removed.

**Comment by ArmyArmyCz** [comment]
I'll make sure to read through the code when I get to PC, I'm currently only on phone.

**Comment by ArmyArmyCz** [comment]
Tested it myself. Automatic outdent doesn't work for me, but that's caused by different keyboard layout, my "}" doesn't require Shift, so nothing you can do about it.

**Pull request merged**
